name: demo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  provider: ^6.1.5
  firebase_messaging: ^15.2.6

  table_calendar: ^3.2.0
  fl_chart: ^1.0.0

  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1

  intl: ^0.20.2
  uuid: ^4.5.1

  cupertino_icons: ^1.0.0

  http: ^1.4.0
  flutter_dotenv: ^5.2.1

  # File operations and sharing
  path_provider: ^2.1.4
  share_plus: ^10.0.3

  # Google Calendar integration dependencies
  googleapis: ^14.0.0
  google_sign_in: ^6.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  assets:
      - lib/Picture/cglobal.jpg
      - GeminiAPI.env
  uses-material-design: true

  

flutter_icons:
  android: true
  ios: true
  image_path: "lib/Picture/cglobal.jpg"
