// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQSDJVvOR7c2Obqqh_yINcv-FaruiWz64',
    appId: '1:972569075106:web:470e9a03eb6d14778fe6fb',
    messagingSenderId: '972569075106',
    projectId: 'calendarexpenseapp',
    authDomain: 'calendarexpenseapp.firebaseapp.com',
    storageBucket: 'calendarexpenseapp.firebasestorage.app',
    measurementId: 'G-Z8HJFFZ8BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbe2rk4ycTRzxKiwTpGwfKRgYrnVN4U6A',
    appId: '1:972569075106:android:18f1bf18bb40dd938fe6fb',
    messagingSenderId: '972569075106',
    projectId: 'calendarexpenseapp',
    storageBucket: 'calendarexpenseapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh1Plt4aEQwzaiSLdcWn731DBi5j9-s7M',
    appId: '1:972569075106:ios:af4f07c6b3352b7c8fe6fb',
    messagingSenderId: '972569075106',
    projectId: 'calendarexpenseapp',
    storageBucket: 'calendarexpenseapp.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQSDJVvOR7c2Obqqh_yINcv-FaruiWz64',
    appId: '1:972569075106:web:9392767ba145afb78fe6fb',
    messagingSenderId: '972569075106',
    projectId: 'calendarexpenseapp',
    authDomain: 'calendarexpenseapp.firebaseapp.com',
    storageBucket: 'calendarexpenseapp.firebasestorage.app',
    measurementId: 'G-V2HZ604P3X',
  );
}
